// For authentication
const LOG_IN_WITH_PASSWORD = "LOG_IN_WITH_PASSWORD";
const LOG_IN_WITH_GOOGLE = "LOG_IN_WITH_GOOGLE";
const SIGN_UP_WITH_PASSWORD = "SIGN_UP_WITH_PASSWORD";
const LOG_OUT = "LOG_OUT";
